import type { SupportedLocale } from '../../../shared/localization';
import { debtApiErrorTranslations } from './debtApiErrorTranslations';
import { debtValidationTranslations } from './debtValidationTranslations';

export const debtResources = {
  en: {
    common: {
      debts: {
        card: {
          actions: {
            delete: 'Delete debt',
            edit: 'Edit debt',
            menuLabel: 'Actions for {{description}}',
            openMenu: 'Open actions for {{description}}',
          },
          dueDate: 'Due',
          dueToday: 'Due today',
          installmentCount: '{{count}} installments',
          onePayment: 'One payment',
          overdue: 'Overdue',
          paid: 'Paid',
          paymentProgress: 'Payment progress for {{description}}',
          remaining: 'Remaining',
          upcoming: 'Upcoming',
        },
        delete: {
          amountLabel: 'Total to delete',
          cancel: 'Cancel',
          confirm: 'Delete debt',
          deleting: 'Deleting',
          description:
            'Are you sure you want to permanently delete "{{description}}"? This action cannot be undone.',
          title: 'Delete debt',
        },
        drawer: {
          close: 'Close debt form',
          description: 'Create a debt for this customer.',
          editDescription: 'Edit this one-payment debt for this customer.',
          editTitle: 'Edit debt',
          createTitle: 'Add debt',
        },
        errors: debtApiErrorTranslations.en,
        form: {
          cancel: 'Cancel',
          addInstallment: 'Add installment',
          customizeInstallments: 'Customize installments',
          currencyLabel: 'Currency',
          descriptionLabel: 'Description',
          descriptionPlaceholder: 'Website redesign',
          dueDateLabel: 'Due date',
          firstInstallmentDueDateLabel: 'First installment due date',
          frequencyLabel: 'Frequency',
          installmentAmountLabel: 'Amount',
          installmentCountLabel: 'Installment count',
          installmentCountGuidance: 'Choose between {{minimum}} and {{maximum}} installments.',
          installmentAmountFieldLabel: 'Installment {{number}} amount',
          installmentDueDateLabel: 'Due date',
          installmentDueDateFieldLabel: 'Installment {{number}} due date',
          installmentNumberLabel: 'Installment',
          installmentPreviewCaption: 'Generated installment schedule',
          installmentPreviewLabel: 'Installment preview',
          installmentSummaryLabel: 'Installment summary',
          installmentSummaryUnavailable: 'Enter valid amounts to calculate the summary.',
          installmentsUnavailable: 'This amount cannot be split into installments.',
          installmentsOption: 'Installments',
          monthlyOption: 'Monthly',
          onePaymentOption: 'One payment',
          paymentPlanLabel: 'Payment plan',
          removeInstallment: 'Remove installment {{number}}',
          debtTotalLabel: 'Debt total',
          scheduleTotalLabel: 'Schedule total',
          remainingAmountLabel: 'Remaining',
          excessAmountLabel: 'Excess',
          resetToAutomaticSchedule: 'Reset to automatic schedule',
          save: 'Save debt',
          saving: 'Saving',
          totalAmountLabel: 'Total amount',
          totalAmountPlaceholder: '125.50',
          weeklyOption: 'Weekly',
        },
        section: {
          empty: 'No debts yet.',
          title: 'Debts',
        },
        search: {
          label: 'Search debts',
          placeholder: 'Search descriptions',
        },
        list: {
          error: {
            title: 'Could not load debts',
          },
          loading: 'Loading debts',
          pagination: {
            label: 'Debt pages',
            nextPage: 'Next page',
            previousPage: 'Previous page',
          },
        },
        toast: {
          create: {
            errorTitle: 'Could not create debt',
            successDescription: '{{description}} was added.',
            successTitle: 'Debt created',
          },
          edit: {
            errorTitle: 'Could not update debt',
            successDescription: '{{description}} was updated.',
            successTitle: 'Debt updated',
          },
          delete: {
            errorTitle: 'Could not delete debt',
            successDescription: '{{description}} was deleted.',
            successTitle: 'Debt deleted',
          },
        },
        validation: debtValidationTranslations.en,
      },
    },
  },
  tr: {
    common: {
      debts: {
        card: {
          actions: {
            delete: 'Borcu sil',
            edit: 'Borcu düzenle',
            menuLabel: '{{description}} işlemleri',
            openMenu: '{{description}} işlemlerini aç',
          },
          dueDate: 'Vade',
          dueToday: 'Vadesi bugün',
          installmentCount: '{{count}} taksit',
          onePayment: 'Tek ödeme',
          overdue: 'Vadesi geçmiş',
          paid: 'Ödenen',
          paymentProgress: '{{description}} ödeme ilerlemesi',
          remaining: 'Kalan',
          upcoming: 'Bekliyor',
        },
        delete: {
          amountLabel: 'Silinecek toplam',
          cancel: 'İptal',
          confirm: 'Borcu sil',
          deleting: 'Siliniyor',
          description:
            '"{{description}}" borcunu kalıcı olarak silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
          title: 'Borcu sil',
        },
        drawer: {
          close: 'Borç formunu kapat',
          description: 'Bu müşteri için bir borç oluşturun.',
          editDescription: 'Bu müşterinin tek ödemeli borcunu düzenleyin.',
          editTitle: 'Borcu düzenle',
          createTitle: 'Borç ekle',
        },
        form: {
          cancel: 'İptal',
          addInstallment: 'Taksit ekle',
          customizeInstallments: 'Taksitleri özelleştir',
          currencyLabel: 'Para birimi',
          descriptionLabel: 'Açıklama',
          descriptionPlaceholder: 'Web sitesi yeniden tasarımı',
          dueDateLabel: 'Vade tarihi',
          firstInstallmentDueDateLabel: 'İlk taksit vade tarihi',
          frequencyLabel: 'Sıklık',
          installmentAmountLabel: 'Tutar',
          installmentCountLabel: 'Taksit sayısı',
          installmentCountGuidance: '{{minimum}} ile {{maximum}} arasında taksit seçin.',
          installmentAmountFieldLabel: '{{number}}. taksit tutarı',
          installmentDueDateLabel: 'Vade tarihi',
          installmentDueDateFieldLabel: '{{number}}. taksit vade tarihi',
          installmentNumberLabel: 'Taksit',
          installmentPreviewCaption: 'Oluşturulan taksit planı',
          installmentPreviewLabel: 'Taksit önizlemesi',
          installmentSummaryLabel: 'Taksit özeti',
          installmentSummaryUnavailable: 'Özeti hesaplamak için geçerli tutarlar girin.',
          installmentsUnavailable: 'Bu tutar taksitlere bölünemez.',
          installmentsOption: 'Taksitler',
          monthlyOption: 'Aylık',
          onePaymentOption: 'Tek ödeme',
          paymentPlanLabel: 'Ödeme planı',
          removeInstallment: '{{number}}. taksiti kaldır',
          debtTotalLabel: 'Borç toplamı',
          scheduleTotalLabel: 'Toplam taksit tutarı',
          remainingAmountLabel: 'Kalan',
          excessAmountLabel: 'Fazla',
          resetToAutomaticSchedule: 'Otomatik plana dön',
          save: 'Borcu kaydet',
          saving: 'Kaydediliyor',
          totalAmountLabel: 'Toplam tutar',
          totalAmountPlaceholder: '125.50',
          weeklyOption: 'Haftalık',
        },
        section: {
          empty: 'Henüz borç yok.',
          title: 'Borçlar',
        },
        search: {
          label: 'Borç ara',
          placeholder: 'Açiklamalarda ara',
        },
        list: {
          error: {
            title: 'Borçlar yüklenemedi',
          },
          loading: 'Borclar yukleniyor',
          pagination: {
            label: 'Borç sayfaları',
            nextPage: 'Sonraki sayfa',
            previousPage: 'Önceki sayfa',
          },
        },
        toast: {
          create: {
            errorTitle: 'Borç oluşturulamadı',
            successDescription: '{{description}} eklendi.',
            successTitle: 'Borç oluşturuldu',
          },
          edit: {
            errorTitle: 'Borç güncellenemedi',
            successDescription: '{{description}} güncellendi.',
            successTitle: 'Borç güncellendi',
          },
          delete: {
            errorTitle: 'Borç silinemedi',
            successDescription: '{{description}} silindi.',
            successTitle: 'Borç silindi',
          },
        },
        validation: debtValidationTranslations.tr,
        errors: debtApiErrorTranslations.tr,
      },
    },
  },
  ar: {
    common: {
      debts: {
        card: {
          actions: {
            delete: 'حذف الدين',
            edit: 'تحرير الدين',
            menuLabel: 'إجراءات {{description}}',
            openMenu: 'فتح إجراءات {{description}}',
          },
          dueDate: 'الاستحقاق',
          dueToday: 'مستحق اليوم',
          installmentCount: '{{count}} أقساط',
          onePayment: 'دفعة واحدة',
          overdue: 'متأخر',
          paid: 'المدفوع',
          paymentProgress: 'تقدم الدفع لـ {{description}}',
          remaining: 'المتبقي',
          upcoming: 'قادم',
        },
        delete: {
          amountLabel: 'الإجمالي المراد حذفه',
          cancel: 'إلغاء',
          confirm: 'حذف الدين',
          deleting: 'جارٍ الحذف',
          description:
            'هل أنت متأكد من حذف الدين "{{description}}" نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.',
          title: 'حذف الدين',
        },
        drawer: {
          close: 'إغلاق نموذج الدين',
          description: 'أنشئ دينًا لهذا العميل.',
          editDescription: 'حرّر الدين ذي الدفعة الواحدة لهذا العميل.',
          editTitle: 'تحرير الدين',
          createTitle: 'إضافة دين',
        },
        form: {
          cancel: 'إلغاء',
          addInstallment: 'إضافة قسط',
          customizeInstallments: 'تخصيص الأقساط',
          currencyLabel: 'العملة',
          descriptionLabel: 'الوصف',
          descriptionPlaceholder: 'إعادة تصميم الموقع الإلكتروني',
          dueDateLabel: 'تاريخ الاستحقاق',
          firstInstallmentDueDateLabel: 'تاريخ استحقاق القسط الأول',
          frequencyLabel: 'التكرار',
          installmentAmountLabel: 'المبلغ',
          installmentCountLabel: 'عدد الأقساط',
          installmentCountGuidance: 'اختر بين {{minimum}} و{{maximum}} أقساط.',
          installmentAmountFieldLabel: 'مبلغ القسط {{number}}',
          installmentDueDateLabel: 'تاريخ الاستحقاق',
          installmentDueDateFieldLabel: 'تاريخ استحقاق القسط {{number}}',
          installmentNumberLabel: 'القسط',
          installmentPreviewCaption: 'جدول الأقساط المُنشأ',
          installmentPreviewLabel: 'معاينة الأقساط',
          installmentSummaryLabel: 'ملخص الأقساط',
          installmentSummaryUnavailable: 'أدخل مبالغ صحيحة لحساب الملخص.',
          installmentsUnavailable: 'لا يمكن تقسيم هذا المبلغ إلى أقساط.',
          installmentsOption: 'أقساط',
          monthlyOption: 'شهريًا',
          onePaymentOption: 'دفعة واحدة',
          paymentPlanLabel: 'خطة الدفع',
          removeInstallment: 'إزالة القسط {{number}}',
          debtTotalLabel: 'إجمالي الدين',
          scheduleTotalLabel: 'إجمالي مبالغ الأقساط',
          remainingAmountLabel: 'المتبقي',
          excessAmountLabel: 'الزيادة',
          resetToAutomaticSchedule: 'إعادة الجدول التلقائي',
          save: 'حفظ الدين',
          saving: 'جارٍ الحفظ',
          totalAmountLabel: 'المبلغ الإجمالي',
          totalAmountPlaceholder: '125.50',
          weeklyOption: 'أسبوعيًا',
        },
        section: {
          empty: 'لا توجد ديون بعد.',
          title: 'الديون',
        },
        search: {
          label: 'ابحث عن الديون',
          placeholder: 'ابحث في الأوصاف',
        },
        list: {
          error: {
            title: 'تعذر تحميل الديون',
          },
          loading: 'جارٍ تحميل الديون',
          pagination: {
            label: 'صفحات الديون',
            nextPage: 'الصفحة التالية',
            previousPage: 'الصفحة السابقة',
          },
        },
        toast: {
          create: {
            errorTitle: 'تعذر إنشاء الدين',
            successDescription: 'تمت إضافة {{description}}.',
            successTitle: 'تم إنشاء الدين',
          },
          edit: {
            errorTitle: 'تعذر تحديث الدين',
            successDescription: 'تم تحديث {{description}}.',
            successTitle: 'تم تحديث الدين',
          },
          delete: {
            errorTitle: 'تعذر حذف الدين',
            successDescription: 'تم حذف {{description}}.',
            successTitle: 'تم حذف الدين',
          },
        },
        validation: debtValidationTranslations.ar,
        errors: debtApiErrorTranslations.ar,
      },
    },
  },
} satisfies Record<SupportedLocale, { common: { debts: Record<string, unknown> } }>;
