import type { SupportedLocale } from '../../../shared/localization';
import { customerApiErrorTranslations } from './customerApiErrorTranslations';
import { customerValidationTranslations } from './customerValidationTranslations';

export const customerResources = {
  en: {
    common: {
      customers: {
        actions: {
          addDebt: 'Add debt',
          create: 'Create customer',
          recordPayment: 'Record payment',
          save: 'Save customer',
          saving: 'Saving',
        },
        create: {
          addressLabel: 'Address',
          addressPlaceholder: 'Optional address',
          cancel: 'Cancel',
          close: 'Close customer form',
          codeLabel: 'Code',
          codePlaceholder: 'ACME-001',
          nameLabel: 'Name',
          namePlaceholder: 'Acme Market',
          phoneNumberLabel: 'Phone number',
          phoneNumberPlaceholder: '+90 555 123 45 67',
          title: 'Create customer',
        },
        details: {
          address: 'Address',
          balance: 'Balance',
          code: 'Code',
          debts: 'Debts',
          debtsEmpty: 'No debts yet.',
          financialSummary: 'Financial summary',
          noAddress: 'No address',
          payments: 'Payments',
          paymentsEmpty: 'No payments yet.',
          phoneNumber: 'Phone',
          totalDebt: 'Total debt',
          totalPaid: 'Total paid',
        },
        errors: customerApiErrorTranslations.en,
        notFound: {
          action: 'Back to Customers',
          detail: 'This customer may have been removed or belongs to another owner.',
          title: 'Customer not found',
        },
        list: {
          actions: {
            menuLabel: 'Actions for {{name}}',
            openDetails: 'Open details',
            openMenu: 'Open actions for {{name}}',
          },
          columns: {
            actions: 'Actions',
            code: 'Code',
            name: 'Name',
            nextDueDate: 'Next due date',
            overdueAmount: 'Overdue amount',
            phone: 'Phone',
            remainingDebt: 'Remaining debt',
          },
          emptyFinancial: {
            nextDueDate: 'No due date',
            overdueAmount: 'No overdue',
            remainingDebt: 'No debt',
          },
          extraCurrencies: {
            count: '+{{count}} currencies',
            countSingular: '+{{count}} currency',
            overdueDialogLabel: 'Overdue amount currencies for {{name}}',
            overdueAriaLabel: 'Show {{count}} more overdue amount currency for {{name}}',
            overdueAriaLabelPlural: 'Show {{count}} more overdue amount currencies for {{name}}',
            remainingDialogLabel: 'Remaining debt currencies for {{name}}',
            remainingAriaLabel: 'Show {{count}} more remaining debt currency for {{name}}',
            remainingAriaLabelPlural: 'Show {{count}} more remaining debt currencies for {{name}}',
          },
          error: {
            title: 'Could not load customers',
          },
          loading: 'Loading customers',
          pagination: {
            label: 'Customer pages',
            nextPage: 'Next page',
            previousPage: 'Previous page',
          },
        },
        page: {
          empty: 'Create your first customer to start tracking debts.',
          title: 'Customers',
        },
        toast: {
          create: {
            errorTitle: 'Could not create customer',
            successDescription: '{{name}} is ready for debt tracking.',
            successTitle: 'Customer created',
          },
        },
        validation: customerValidationTranslations.en,
      },
    },
  },
  tr: {
    common: {
      customers: {
        actions: {
          addDebt: 'Borc ekle',
          create: 'Musteri olustur',
          recordPayment: 'Odeme kaydet',
          save: 'Musteriyi kaydet',
          saving: 'Kaydediliyor',
        },
        create: {
          addressLabel: 'Adres',
          addressPlaceholder: 'Istege bagli adres',
          cancel: 'Iptal',
          close: 'Musteri formunu kapat',
          codeLabel: 'Kod',
          codePlaceholder: 'ACME-001',
          nameLabel: 'Ad',
          namePlaceholder: 'Acme Market',
          phoneNumberLabel: 'Telefon numarasi',
          phoneNumberPlaceholder: '+90 555 123 45 67',
          title: 'Musteri olustur',
        },
        details: {
          address: 'Adres',
          balance: 'Bakiye',
          code: 'Kod',
          debts: 'Borclar',
          debtsEmpty: 'Henuz borc yok.',
          financialSummary: 'Finansal ozet',
          noAddress: 'Adres yok',
          payments: 'Odemeler',
          paymentsEmpty: 'Henuz odeme yok.',
          phoneNumber: 'Telefon',
          totalDebt: 'Toplam borc',
          totalPaid: 'Toplam odenen',
        },
        errors: customerApiErrorTranslations.tr,
        notFound: {
          action: 'Musterilere don',
          detail: 'Bu musteri silinmis veya baska bir sahibe ait olabilir.',
          title: 'Musteri bulunamadi',
        },
        list: {
          actions: {
            menuLabel: '{{name}} icin islemler',
            openDetails: 'Detaylari ac',
            openMenu: '{{name}} icin islemleri ac',
          },
          columns: {
            actions: 'Islemler',
            code: 'Kod',
            name: 'Ad',
            nextDueDate: 'Sonraki vade',
            overdueAmount: 'Geciken tutar',
            phone: 'Telefon',
            remainingDebt: 'Kalan borc',
          },
          emptyFinancial: {
            nextDueDate: 'Vade yok',
            overdueAmount: 'Geciken yok',
            remainingDebt: 'Borc yok',
          },
          extraCurrencies: {
            count: '+{{count}} para birimi',
            countSingular: '+{{count}} para birimi',
            overdueDialogLabel: '{{name}} icin geciken tutar para birimleri',
            overdueAriaLabel: '{{name}} icin {{count}} ek geciken tutar para birimini goster',
            overdueAriaLabelPlural: '{{name}} icin {{count}} ek geciken tutar para birimini goster',
            remainingDialogLabel: '{{name}} icin kalan borc para birimleri',
            remainingAriaLabel: '{{name}} icin {{count}} ek kalan borc para birimini goster',
            remainingAriaLabelPlural: '{{name}} icin {{count}} ek kalan borc para birimini goster',
          },
          error: {
            title: 'Musteriler yuklenemedi',
          },
          loading: 'Musteriler yukleniyor',
          pagination: {
            label: 'Musteri sayfalari',
            nextPage: 'Sonraki sayfa',
            previousPage: 'Onceki sayfa',
          },
        },
        page: {
          empty: 'Borc takibine baslamak icin ilk musteriyi olusturun.',
          title: 'Musteriler',
        },
        toast: {
          create: {
            errorTitle: 'Musteri olusturulamadi',
            successDescription: '{{name}} borc takibi icin hazir.',
            successTitle: 'Musteri olusturuldu',
          },
        },
        validation: customerValidationTranslations.tr,
      },
    },
  },
  ar: {
    common: {
      customers: {
        actions: {
          addDebt: 'أضف دينًا',
          create: 'أنشئ عميلًا',
          recordPayment: 'سجل دفعة',
          save: 'احفظ العميل',
          saving: 'جارٍ الحفظ',
        },
        create: {
          addressLabel: 'العنوان',
          addressPlaceholder: 'عنوان اختياري',
          cancel: 'إلغاء',
          close: 'أغلق نموذج العميل',
          codeLabel: 'الرمز',
          codePlaceholder: 'ACME-001',
          nameLabel: 'الاسم',
          namePlaceholder: 'سوق أكمي',
          phoneNumberLabel: 'رقم الهاتف',
          phoneNumberPlaceholder: '+90 555 123 45 67',
          title: 'أنشئ عميلًا',
        },
        details: {
          address: 'العنوان',
          balance: 'الرصيد',
          code: 'الرمز',
          debts: 'الديون',
          debtsEmpty: 'لا توجد ديون بعد.',
          financialSummary: 'الملخص المالي',
          noAddress: 'لا يوجد عنوان',
          payments: 'الدفعات',
          paymentsEmpty: 'لا توجد دفعات بعد.',
          phoneNumber: 'الهاتف',
          totalDebt: 'إجمالي الدين',
          totalPaid: 'إجمالي المدفوع',
        },
        errors: customerApiErrorTranslations.ar,
        list: {
          actions: {
            menuLabel: 'إجراءات {{name}}',
            openDetails: 'افتح التفاصيل',
            openMenu: 'فتح إجراءات {{name}}',
          },
          columns: {
            actions: 'الإجراءات',
            code: 'الرمز',
            name: 'الاسم',
            nextDueDate: 'تاريخ الاستحقاق التالي',
            overdueAmount: 'المبلغ المتأخر',
            phone: 'الهاتف',
            remainingDebt: 'الدين المتبقي',
          },
          emptyFinancial: {
            nextDueDate: 'لا يوجد تاريخ استحقاق',
            overdueAmount: 'لا يوجد متأخرات',
            remainingDebt: 'لا يوجد دين',
          },
          extraCurrencies: {
            count: '+{{count}} عملات',
            countSingular: '+{{count}} عملة',
            overdueDialogLabel: 'عملات المبلغ المتأخر لـ {{name}}',
            overdueAriaLabel: 'إظهار {{count}} عملة مبلغ متأخر إضافية لـ {{name}}',
            overdueAriaLabelPlural: 'إظهار {{count}} عملات مبلغ متأخر إضافية لـ {{name}}',
            remainingDialogLabel: 'عملات الدين المتبقي لـ {{name}}',
            remainingAriaLabel: 'إظهار {{count}} عملة دين متبق إضافية لـ {{name}}',
            remainingAriaLabelPlural: 'إظهار {{count}} عملات دين متبق إضافية لـ {{name}}',
          },
          error: {
            title: 'تعذر تحميل العملاء',
          },
          loading: 'جارٍ تحميل العملاء',
          pagination: {
            label: 'صفحات العملاء',
            nextPage: 'الصفحة التالية',
            previousPage: 'الصفحة السابقة',
          },
        },
        notFound: {
          action: 'العودة إلى العملاء',
          detail: 'قد يكون هذا العميل محذوفًا أو يخص مالكًا آخر.',
          title: 'لم يتم العثور على العميل',
        },
        page: {
          empty: 'أنشئ أول عميل لبدء متابعة الديون.',
          title: 'العملاء',
        },
        toast: {
          create: {
            errorTitle: 'تعذر إنشاء العميل',
            successDescription: '{{name}} جاهز لمتابعة الديون.',
            successTitle: 'تم إنشاء العميل',
          },
        },
        validation: customerValidationTranslations.ar,
      },
    },
  },
} satisfies Record<
  SupportedLocale,
  { common: { customers: Record<string, unknown> } }
>;
